### ISSUE TITLE
Quote the instruction "$(pwd):/datos"

### ISSUE THREAD

**Issue by jlrzarcor** [palmoreck/dockerfiles#2]
Hola Erick:

Traté de ejecutar la instrucción

**docker run --rm -v $(pwd):/datos --name jupyterlab_prope_r_kernel_tidyverse -p 8888:8888 -d $REPO_URL:$JUPYTERLAB_VERSION**

y no se ejecuto. Buscando un poco de referencia, encontré que es necesario entrecomillar "$(pwd):/datos", con lo que se ejecutó adecuadamente la instrucción.

**Comment by palmoreck** [comment]
@jlrzarcor hola 

¿Ejecutaste tal comando en un sistema Windows? ¿previamente definiste las variables de `REPO_URL` y `JUPYTERLAB_VERSION`?

Saludos,

Erick

**Comment by jlrzarcor** [comment]
La plataforma de mi lap es Windows 10 Home.
Si, cargue las variables previamente de acuerdo al directorio que quería montar en mi máquina virtual.
